
import java.sql.SQLException;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import model.Pelanggan;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author HADI PC
 */
public class HalamanPelanggan extends javax.swing.JPanel {

    /**
     * Creates new form HalamanMobil
     */
    public HalamanPelanggan() {
        initComponents();

        loadPelangganList();  // Changed to load Pelanggan list
        listPelanggan.addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                Pelanggan selectedPelanggan = listPelanggan.getSelectedValue();
                if (selectedPelanggan != null) {
                    // Tampilkan detail pelanggan di form
                    txtNamaPengguna.setText(selectedPelanggan.nama());
                    txtAlamat.setText(selectedPelanggan.alamat());
                    txtNomorTelepon.setText(selectedPelanggan.nomorTelepon());
                    txtEmail.setText(selectedPelanggan.email());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaPengguna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomorTelepon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPelanggan = new javax.swing.JList<>();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));
        jPanel4.setLayout(new java.awt.GridLayout(2, 4, 12, 8));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nama Pengguna");
        jPanel4.add(jLabel2);
        jPanel4.add(txtNamaPengguna);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Alamat");
        jPanel4.add(jLabel3);
        jPanel4.add(txtAlamat);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Nomor Telepon");
        jPanel4.add(jLabel4);

        txtNomorTelepon.setInputVerifier(new PhoneNumberVerifier());
        jPanel4.add(txtNomorTelepon);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Email");
        jPanel4.add(jLabel5);

        txtEmail.setInputVerifier(new EmailVerifier());
        jPanel4.add(txtEmail);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 4));

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel6.add(btnSimpan);

        btnUbah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setPreferredSize(new java.awt.Dimension(150, 50));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel6.add(btnUbah);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(150, 50));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel6.add(btnHapus);

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(150, 50));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        txtCari.setPreferredSize(new java.awt.Dimension(360, 30));
        jPanel7.add(txtCari);

        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel7.add(btnCari);

        jPanel1.add(jPanel7, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));

        listPelanggan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listPelanggan);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Pelanggan pelanggan = getPelangganFromInput();
        if (pelanggan == null) {
            return;
        }

        try {
            pelanggan.save();
            loadPelangganList();
            clearInputFields();
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan pelanggan: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        Pelanggan selectedPelanggan = listPelanggan.getSelectedValue();
        if (selectedPelanggan == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih pelanggan yang ingin diubah!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Pelanggan updatedPelanggan = getPelangganFromInput(selectedPelanggan.idPelanggan());
        if (updatedPelanggan == null) {
            return;
        }

        try {
            updatedPelanggan.update();  // Update Pelanggan instead of Mobil
            loadPelangganList();
            clearInputFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Data pelanggan berhasil diperbarui!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui pelanggan: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        Pelanggan selectedPelanggan = listPelanggan.getSelectedValue();
        if (selectedPelanggan == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih pelanggan yang ingin dihapus!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus pelanggan " + selectedPelanggan.nama() + "?",
                "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {
            selectedPelanggan.delete(); // Delete Pelanggan instead of Mobil
            loadPelangganList();
            clearInputFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Pelanggan berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus pelanggan: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        loadPelangganList(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearInputFields();
        txtCari.setText("");
        loadPelangganList();
    }//GEN-LAST:event_btnResetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadPelangganList();
        txtCari.setText("");
        clearInputFields();
    }//GEN-LAST:event_formComponentShown

    private void loadPelangganList() {
        loadPelangganList(null);
    }

    private void loadPelangganList(String keyword) {
        try {
            // Get data pelanggan instead of mobil
            List<Pelanggan> pelangganList = Pelanggan.getAll(keyword);

            DefaultListModel<Pelanggan> listModel = new DefaultListModel<>();
            for (Pelanggan pelanggan : pelangganList) {
                listModel.addElement(pelanggan);
            }

            listPelanggan.setModel(listModel);
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data pelanggan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private Pelanggan getPelangganFromInput() {
        return getPelangganFromInput(null);
    }

    private Pelanggan getPelangganFromInput(Integer id) {
        String nama = txtNamaPengguna.getText().trim();
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama pelanggan tidak boleh kosong!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }

        String alamat = txtAlamat.getText().trim();
        if (alamat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }

        String nomorTelepon = txtNomorTelepon.getText().trim();
        if (nomorTelepon.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nomor telepon tidak boleh kosong!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }

        String email = txtEmail.getText().trim();
        if (email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Email tidak boleh kosong!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }

        // Create Pelanggan from input
        if (id != null) {
            return new Pelanggan(id, nama, alamat, nomorTelepon, email);
        } else {
            return new Pelanggan(nama, alamat, nomorTelepon, email);
        }
    }

    // Phone number verifier (validates only digits and length check)
    class PhoneNumberVerifier extends InputVerifier {

        @Override
        public boolean verify(JComponent input) {
            String telepon = ((javax.swing.JTextField) input).getText().trim();
            if (telepon.isEmpty()) {
                return true;
            }

            // Validating if the phone number starts with "08", "+62" or "62" and has 10-13 digits
            if (telepon.matches("(08\\d{8,11}|\\+62\\d{9,12})")) {
                return true;
            } else {
                javax.swing.JOptionPane.showMessageDialog(input, "Nomor telepon tidak valid!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                ((javax.swing.JTextField) input).setText("");
                return true;
            }

        }
    }

    // Email verifier (validates email format)
    class EmailVerifier extends InputVerifier {

        @Override
        public boolean verify(JComponent input) {
            String email = ((javax.swing.JTextField) input).getText().trim();
            if (email.isEmpty()) {
                return true;
            }

            // Regex for simple email validation
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            if (Pattern.matches(emailRegex, email)) {
                return true;
            } else {
                javax.swing.JOptionPane.showMessageDialog(input, "Email tidak valid!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                ((javax.swing.JTextField) input).setText("");
                return true;
            }
        }
    }

    private void clearInputFields() {
        txtNamaPengguna.setText("");
        txtAlamat.setText("");
        txtNomorTelepon.setText("");
        txtEmail.setText("");
        listPelanggan.clearSelection(); // Hapus seleksi pada JList
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JList<Pelanggan> listPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaPengguna;
    private javax.swing.JTextField txtNomorTelepon;
    // End of variables declaration//GEN-END:variables
}
