
import com.lowagie.text.DocumentException;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import model.Mobil;
import model.Pelanggan;
import model.Transaksi;
import report.ReportMobilTersedia;
import report.ReportLaba;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author HADI PC
 */
public class HalamanHome extends javax.swing.JPanel {

    /**
     * Creates new form HalamanHome
     */
    public HalamanHome() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblJumlahMobil = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblJumlahMobilTersedia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblJumlahPelanggan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblJumlahTransaksi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblJumlahTransaksiTahunIni = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblJumlahTransaksiBulanIni = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnLaporanMobilTersedia = new javax.swing.JButton();
        btnLaporanTransaksi = new javax.swing.JButton();
        btnLaporanLaba = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Aplikasi Rental Mobil");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(54, 36, 24, 36));
        add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 36, 0, 36));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(36, 0, 36, 0));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 24, 12));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Data Mobil", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblJumlahMobil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahMobil.setText("-");
        lblJumlahMobil.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel2.add(lblJumlahMobil, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Mobil (tersedia)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        lblJumlahMobilTersedia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahMobilTersedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahMobilTersedia.setText("-");
        lblJumlahMobilTersedia.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel7.add(lblJumlahMobilTersedia, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Data Pelanggan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        lblJumlahPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahPelanggan.setText("-");
        lblJumlahPelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel3.add(lblJumlahPelanggan, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Data Transaksi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        lblJumlahTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahTransaksi.setText("-");
        lblJumlahTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel4.add(lblJumlahTransaksi, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Transaksi (tahun ini)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        lblJumlahTransaksiTahunIni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahTransaksiTahunIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahTransaksiTahunIni.setText("-");
        lblJumlahTransaksiTahunIni.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel5.add(lblJumlahTransaksiTahunIni, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Transaksi (bulan ini)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        lblJumlahTransaksiBulanIni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJumlahTransaksiBulanIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahTransaksiBulanIni.setText("-");
        lblJumlahTransaksiBulanIni.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 12, 24, 12));
        jPanel6.add(lblJumlahTransaksiBulanIni, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel8.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnLaporanMobilTersedia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLaporanMobilTersedia.setText("Laporan Mobil Tersedia");
        btnLaporanMobilTersedia.setPreferredSize(new java.awt.Dimension(180, 48));
        btnLaporanMobilTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanMobilTersediaActionPerformed(evt);
            }
        });
        jPanel10.add(btnLaporanMobilTersedia);

        btnLaporanTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLaporanTransaksi.setText("Laporan Transaksi");
        btnLaporanTransaksi.setPreferredSize(new java.awt.Dimension(180, 48));
        btnLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanTransaksiActionPerformed(evt);
            }
        });
        jPanel10.add(btnLaporanTransaksi);

        btnLaporanLaba.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLaporanLaba.setText("Laporan Laba");
        btnLaporanLaba.setPreferredSize(new java.awt.Dimension(180, 48));
        btnLaporanLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanLabaActionPerformed(evt);
            }
        });
        jPanel10.add(btnLaporanLaba);

        jPanel9.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel8, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadData();
    }//GEN-LAST:event_formComponentShown

    private void btnLaporanLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanLabaActionPerformed
        // Membuat JFileChooser untuk memilih lokasi penyimpanan PDF
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Lokasi untuk Menyimpan Laporan Laba");
        fileChooser.setSelectedFile(new java.io.File("Laporan_Laba.pdf")); // Nama default file
        fileChooser.setCurrentDirectory(new java.io.File(".")); // Menetapkan folder default ke folder sekarang

        // Mengatur filter file hanya untuk file PDF
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("PDF Documents", "pdf"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Pastikan file berformat .pdf
            if (!filePath.endsWith(".pdf")) {
                filePath += ".pdf";
            }

            // Panggil metode untuk membuat laporan penghasilan
            try {
                ReportLaba.generate(filePath);
                javax.swing.JOptionPane.showMessageDialog(this, "Laporan laba berhasil dibuat!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                Desktop.getDesktop().open(new java.io.File(filePath));
            } catch (DocumentException | HeadlessException | IOException | SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat laporan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLaporanLabaActionPerformed

    private void btnLaporanMobilTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanMobilTersediaActionPerformed
        // Membuat JFileChooser untuk memilih lokasi penyimpanan PDF
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Lokasi untuk Menyimpan Laporan Mobil Tersedia");
        fileChooser.setSelectedFile(new java.io.File("Laporan_Mobil_Tersedia.pdf")); // Nama default file
        fileChooser.setCurrentDirectory(new java.io.File(".")); // Menetapkan folder default ke folder sekarang

        // Mengatur filter file hanya untuk file PDF
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("PDF Documents", "pdf"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Pastikan file berformat .pdf
            if (!filePath.endsWith(".pdf")) {
                filePath += ".pdf";
            }

            // Panggil metode untuk membuat laporan mobil tersedia
            try {
                ReportMobilTersedia.generate(filePath);
                javax.swing.JOptionPane.showMessageDialog(this, "Laporan mobil tersedia berhasil dibuat!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                Desktop.getDesktop().open(new java.io.File(filePath));
            } catch (DocumentException | HeadlessException | IOException | SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat laporan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLaporanMobilTersediaActionPerformed

    private void btnLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanTransaksiActionPerformed

    private void loadData() {
        try {
            lblJumlahMobil.setText(Mobil.getAll().size() + " Mobil");
            lblJumlahMobilTersedia.setText(Mobil.getAllAvailable().size() + " Mobil");
            lblJumlahPelanggan.setText(Pelanggan.getAll().size() + " Pelanggan");
            lblJumlahTransaksi.setText(Transaksi.getAll().size() + " Transaksi");
            lblJumlahTransaksiTahunIni.setText(Transaksi.getAllThisYear().size() + " Transaksi");
            lblJumlahTransaksiBulanIni.setText(Transaksi.getAllThisMonth().size() + " Transaksi");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporanLaba;
    private javax.swing.JButton btnLaporanMobilTersedia;
    private javax.swing.JButton btnLaporanTransaksi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblJumlahMobil;
    private javax.swing.JLabel lblJumlahMobilTersedia;
    private javax.swing.JLabel lblJumlahPelanggan;
    private javax.swing.JLabel lblJumlahTransaksi;
    private javax.swing.JLabel lblJumlahTransaksiBulanIni;
    private javax.swing.JLabel lblJumlahTransaksiTahunIni;
    // End of variables declaration//GEN-END:variables
}
